# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Entry

# Model Form Field configuration
form: $/octohelp/importexport/models/entries/fields.yaml

# Model Class name
modelClass: Octohelp\Importexport\Models\Entries

# Default redirect location
defaultRedirect: octohelp/importexport/entries

# Create page
create:
    title: Create Entry
    redirect: octohelp/importexport/entries/update/:id
    redirectClose: octohelp/importexport/entries

# Update page
update:
    title: Edit Entry
    redirect: octohelp/importexport/entries
    redirectClose: octohelp/importexport/entries

# Preview page
preview:
    title: Preview Entry